environment:
  entities_file: "config/entity_config_guam_scenario.json"
  scenario_file: "config/scenarios/scenario_guam_1000km_west.yaml"
  logging_config: "config/logging.yaml"
  map_tool_file: "logs/map_tool_output.csv"
  max_time: 2100
